name: Deploy to DigitalOcean

on:
  push:
    branches:
      - new

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into Droplet and start build
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
        run: |
          ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa $DROPLET_USER@$DROPLET_IP "cd /var/www/bartu-ninja/ && git pull && npm install && npm run build"
